import './globals.css';

import { ThemeWrapper } from '@/components/theme';
import { GeistMono } from 'geist/font/mono';
import { GeistSans } from 'geist/font/sans';
import { Warning } from './components/ui';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body className="relative grid min-h-screen font-body text-lg font-medium dark:bg-grey-900 dark:text-grey-200 bg-grey-200 text-grey-900">
        <Warning />
        <ThemeWrapper>{children}</ThemeWrapper>
      </body>
    </html>
  );
}
